server:
  port: 9090
  tomcat:
    threads:
      max: 50

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: ${db_pass}
#  jpa:                           Dialect property is optional if we will not provide then spring will
#    properties:                  automatically detect dialect property.
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update